name: Q5 Playwright Scraper

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright requests pandas lxml
          playwright install chromium

      - name: Run Scraper - 24f1000656@ds.study.iitm.ac.in
        run: |
          python scrape.py
